name: Checkstyle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkstyle with Maven
        run: mvn checkstyle:checkstyle -DskipTests